apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
spec:
  replicas: 1  # Кількість реплік для Deployment
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:latest
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
  volumes:
    - name: fluent-bit-config
      configMap:
        name: {{ .Values.fluentBit.configMap.name }}
        items:
          - key: {{ .Values.fluentBit.configMap.key }}
            path: fluent-bit.conf