{{- if .Values.fluentBit.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: {{ .Values.fluentBit.image.registry }}/{{ .Values.fluentBit.image.repository }}:{{ .Values.fluentBit.image.tag }}
          volumeMounts:
            - name: docker-metadata-lua
              mountPath: /fluent-bit/bin/
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
          ports:
            - containerPort: 3001
      volumes:
        - name: fluent-bit-config
          configMap:
            name: {{ .Values.fluentBit.configMap.name }}
            key: {{ .Values.fluentBit.configMap.key }}
        - name: docker-metadata-lua
          configMap:
            name: {{ .Values.fluentBit.configMap.luaName }}
            key: {{ .Values.fluentBit.configMap.luaKey }}
{{- end }}
