{{- if .Values.fluentBit.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: {{ .Values.fluentBit.image.registry }}/{{ .Values.fluentBit.image.repository }}:{{ .Values.fluentBit.image.tag }}
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
          args:
            - "-c"
            - "/fluent-bit/etc/fluent-bit.conf"
      volumes:
        - name: fluent-bit-config
          configMap:
            name: {{ .Values.fluentBit.configMap.name }}
            items:
              - key: {{ .Values.fluentBit.configMap.key }}
                path: fluent-bit.conf
              - key: {{ .Values.fluentBit.configMap.luaKey }}
                path: docker-metadata.lua
{{- end }}
