{{- if .Values.fluentBit.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: {{ .Values.fluentBit.image.registry }}/{{ .Values.fluentBit.image.repository }}:{{ .Values.fluentBit.image.tag }}
          volumeMounts:
            - name: fluent-bit-config-volume
              mountPath: /fluent-bit/etc
            - name: docker-metadata-lua
              mountPath: /fluent-bit/bin/docker-metadata.lua
          ports:
            - "3001:3001"
{{- end }}
