apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      version: 1
      editable: false
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      version: 1
      editable: false
{{- end }}
