apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: kbot  # Replace with your actual namespace
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100