{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: {{ .Values.loki.image.registry }}/{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
          args:
            - "--config.file=/etc/loki/loki-local-config.yaml"
{{- end }}
