{{- if .Values.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: {{ .Values.loki.image.registry }}/{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}
          volumeMounts:
            - name: {{ .Values.loki.volumes.name }}
              mountPath: /etc/loki/local-config.yaml
              subPath: local-config.yaml
          ports:
            - containerPort: 3100
          args:
            - "-config.file=/etc/loki/local-config.yaml"
      volumes:
        - name: {{ .Values.loki.volumes.name }}
          configMap:
            name: {{ .Values.loki.configMap.name }}
            key: {{ .Values.loki.configMap.key }}
{{- end }}
