apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.configMap.name }}
data:
  otel-collector-config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: "0.0.0.0:3030"

    exporters:
      logging: {}
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [loki]
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [logging,prometheus]
spec:
  mode: daemonset
  hostNetwork: true
