{{- if .Values.otelOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-operator
  template:
    metadata:
      labels:
        app: otel-operator
    spec:
      containers:
        - name: otel-operator
          image: otel/opentelemetry-operator:latest
{{- end }}
