#!/bin/bash

script_url="https://raw.githubusercontent.com/vsk44/kbot/main/scripts/git-leak-pre-commit"

# Get the path to .git/hooks
hooks_dir=$(git rev-parse --git-dir)/hooks

# Download the script
curl -o "$hooks_dir/git-leak-pre-commit" "$script_url"

# Grant executive rights
chmod +x "$hooks_dir/git-leak-pre-commit"

echo "Git Leaks pre-commit hook installed successfully!"