# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "docker.io"
  repository: "vsk4/kbot"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.6-fe24d35"
  arch: amd64
  os: linux
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
metricsHost:
  name: "collector:4317"

otelOperator:
  enabled: false
  image:
    registry: "otel"
    repository: "opentelemetry-operator"
    tag: "latest"
    arch: amd64
    os: linux

otelCollector:
  enabled: true
  image:
    registry: "otel"
    repository: "opentelemetry-collector-contrib"
    tag: "0.78.0"
    arch: amd64
    os: linux
  volumes:
    - name: otel-collector-config
  configMap:
      name: otel-collector-configmap

fluentBit:
  enabled: true
  image:
    registry: "fluent"
    repository: "fluent-bit"
    tag: "latest"
    arch: amd64
    os: linux
  configMap:
    name: fluent-bit-config
    key: fluent-bit.conf 
    luaName: docker-metadata-lua
    luaKey: docker-metadata.lua

loki:
  enabled: true
  image:
    registry: "grafana"
    repository: "loki"
    tag: "2.8.2"
    arch: amd64
    os: linux
  authEnabled: false  # Додали новий параметр
  server:
    httpListenPort: 3100
    grpcListenPort: 9096
  common:
    instanceAddr: 127.0.0.1
    pathPrefix: /tmp/loki
    storage:
      filesystem:
        chunksDirectory: /tmp/loki/chunks
        rulesDirectory: /tmp/loki/rules
    replicationFactor: 1
    ring:
      kvstore:
        store: inmemory
  queryRange:
    resultsCache:
      cache:
        embeddedCache:
          enabled: true
          maxSizeMb: 100
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        objectStore: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
  ruler:
    alertmanagerUrl: http://localhost:9093
  analytics:
    reportingEnabled: false

prometheus:
  enabled: true
  image:
    registry: "prom"
    repository: "prometheus"
    tag: "latest"
    arch: amd64
    os: linux
  scrapeInterval: 15s
  evaluationInterval: 15s
  additionalScrapeConfigs:
    - job_name: otel_collector
      scrape_interval: 5s
      static_configs:
        - targets: ['collector:8889']
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
        
grafana:
  enabled: true
  image:
    registry: "grafana"
    repository: "grafana"
    tag: "9.4.3"
  provisioning:
    datasources: true
  env:
    - name: GF_AUTH_ANONYMOUS_ENABLED
      value: "true"
    - name: GF_AUTH_ANONYMOUS_ORG_ROLE
      value: "Admin"
    - name: GF_AUTH_DISABLE_LOGIN_FORM
      value: "true"
    - name: GF_FEATURE_TOGGLES_ENABLE
      value: "traceqlEditor"
    - name: GF_SERVER_HTTP_PORT
      value: "3002"
  configMap:
    name: grafana-config
    data:
      grafana.yaml: |-
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          uid: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
          jsonData:
            httpMethod: GET
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: true