# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "docker.io"
  repository: "vsk4/kbot"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.6-fe24d35"
  arch: amd64
  os: linux
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
metricsHost:
  name: "collector:4317"

otelOperator:
  enabled: false
  image:
    registry: "otel"
    repository: "opentelemetry-operator"
    tag: "latest"
    arch: amd64
    os: linux

otelCollector:
  enabled: true
  image:
    registry: "otel"
    repository: "opentelemetry-collector-contrib"
    tag: "0.92.0"
    arch: amd64
    os: linux
  volumes:
      name: otel-collector-config
  configMap:
      name: otel-collector-configmap
      key: otel-collector-config.yaml

fluentBit:
  enabled: true
  image:
    registry: "fluent"
    repository: "fluent-bit"
    tag: "latest"
    arch: amd64
    os: linux
  configMap:
    name: fluent-bit-config
    key: fluent-bit.conf 
    luaName: docker-metadata-lua
    luaKey: docker-metadata.lua

loki:
  enabled: true
  image:
    registry: "grafana"
    repository: "loki"
    tag: "2.8.2"
    arch: amd64
    os: linux
  volumes:
    name: loki-local-config
  configMap:
    name: loki-configmap
    key: local-config.yaml


prometheus:
  enabled: true
  image:
    registry: "prom"
    repository: "prometheus"
    tag: "v2.49.0"
    arch: amd64
    os: linux
  volumes:
    name: prometheus-config  # Оновлена назва ключа volumes
  configMap:
    name: prometheus-configmap
    key: prometheus.yaml
  
        
grafana:
  enabled: true
  image:
    registry: "grafana"
    repository: "grafana"
    tag: "9.4.3"
  volumes:
    name: grafana-config
  configMap:
    name: grafana-configmap
    key: datasources.yaml